### ISSUE TITLE
Cannot find in Maven Central Repo

### ISSUE THREAD

**Issue by hktonylee** [mattgawarecki/play-jammies#1]
I added "com.mattgawarecki.play" % "jammies" % "latest.stable" to `build.sbt` but it shows that

```
[error] (*:update) sbt.ResolveException: unresolved dependency: com.mattgawarecki.play#jammies;latest.stable: not found
```

This repo also does not exist in [Maven Central Repo](http://search.maven.org/#search%7Cga%7C1%7Cmattgawarecki) too.

**Comment by mattgawarecki** [comment]
Hey, thanks for letting me know about this. Honestly I wasn't expecting a lot of use out of this package, but I'm glad somebody's looking at it! I'm investigating getting it uploaded to the Maven Central Repo right now. I'll follow up soon.

**Comment by mattgawarecki** [comment]
Just made a ticket with Sonatype to get things set up on their repository.

**Comment by mattgawarecki** [comment]
Update: I've got a release pending in Sonatype's Nexus repository. Once they verify it's good and rsync is set up for the Maven Central Repo, version 1.0.0 will be live.

**Comment by mattgawarecki** [comment]
Waiting for Maven Central's rsync job to pick up the release and make it publicly available.

**Comment by mattgawarecki** [comment]
Package is now available and searchable on Maven Central. I'll wait for you to verify, @hktonylee, and if everything's good, feel free to close the issue. If I don't hear back, I'll just close it in around a week or so.

**Comment by mattgawarecki** [comment]
It's been almost two weeks now without any comments on the issue, and I believe it to be taken care of. Closing as resolved.
